services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./:/var/www/html
    networks: [laravel]
    healthcheck:
      test: [ "CMD","php-fpm", "-t", "php -r 'exit((bool) @fsockopen(\"127.0.0.1\",9000));'"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      db:
        condition: service_started

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    networks: [laravel]
    env_file:
      - ./.env.nginx
    ports:
      - "${PORT:-80}:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      app:
        condition: service_started

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - ./.env.database
    user: "${SUPER_USER:-postgres}"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks: [laravel]

networks:
  laravel:
    driver: bridge

volumes:
  app_src:
  dbdata:
